#服务端口
server:
  port: 8130
  #服务名
  servlet:
    application-display-name: iuzx-aliyunoss

spring:
  profiles:
    #环境设置：dev、test、prod
    active: dev

#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI4FdtGrnJG9aUvB6YrCng
      accessKeySecret: wCirttSCIEO2daDjNQObpCGrbqnFV8
      bucketName: iuzx-file
      filehost: avatar

